Algoritmo "Exercicio_6"
// Função: Ler 10 numeros inteiros e apresentar sua soma
// Disciplina   : Programação e Algoritmos
// Professora   : Cintia Maria de Araujo Pinho
// Autor(a)     : Luiz Henrique da Silva Lima
Var
num, soma, c:inteiro

Inicio

para c<-1 ate 10 faca
escreval
escreval("Informe o ",c,"° a ser somado...")
leia(num)
soma <- num+soma
fimpara

escreval
escreval("O resultado final é de:",soma)


Fimalgoritmo