Algoritmo "Exercicio_2"
// Função: Imprimir a tabuada de um número escolhido pelo usuário
// Disciplina   : Programação e Algoritmos
// Professora   : Cintia Maria de Araujo Pinho
// Autor(a)     : Luiz Henrique da Silva Lima
Var
cont,num:inteiro

Inicio
escreval("Escreva um número: ")
leia(num)


para cont de 1 ate 10 faca
   escreval(num," x", cont," = ",num*cont)
fimpara


Fimalgoritmo