Algoritmo "Area_do_quadrado"
// Disciplina   : Programação e Algoritmos
// Professor   : Cintia Maria de Araujo Pinho
// Autor(a)    : Luiz Henrique da Silva Lima
// Data atual  : 10/03/2021
Var
   //Declarações das variaveis

   lado, area: real

Inicio

   //entrada de dados
   escreva("Digite o Lado do Quadrado:")
   leia(lado)
   
   //processamento
   area <- lado*lado
   
   //saida
   escreva("A área do quadrado é:",area,"m2")
   

Fimalgoritmo